
        <div class="row">
            <div class="col-md-8">
            <div class="card ">
              <div class="card-header d-none d-sm-none d-md-block  text-right">
                <a class="btn btn-outline-primary" href="<?php echo $link_volver?>">
                    <i class="fas fa-chevron-left"></i> Volver
                </a>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.modulo_id")?>
                  <div class="form-group">
                    <label for="a_modulo" class="text-primary"> Módulo</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                       <label for="a_perfil" class="text-primary"> Nombre del Perfil</label>
                       <?php echo Form::input("text","a.perfil", ' class="form-control" maxlength="45" placeholder="Ingrese el Perfil" ')?>
                  </div>
                  <div class="form-group">
                       <label for="a_precio" class="text-primary"> Precio</label>
                       <?php echo Form::input("text","a.precio", ' class="form-control" maxlength="8" placeholder="Precio Mensual" ')?>
                  </div>
                  <div class="form-group">
                       <label for="a_admin" class="text-primary"> Perfil Administrador</label>
                       <?php echo Form::select("a.admin", Perfil::$ADMIN,' class="form-control" ')?>
                  </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-6 m-1">
                            <button type="submit" class="btn btn-outline-primary btn-block">
                                <i class="far fa-save"></i> 
                                Registrar
                            </button>
                        </div>
                        <div class="col-md-5 m-1">
                            <a class="btn btn-outline-primary btn-block" href="<?php echo $link_volver?>">
                                <i class="fas fa-chevron-left"></i> Volver
                            </a>
                        </div>
                    </div>
                </div>
              </form>
            </div>
                
           </div>
        </div>
        <!-- /.row -->

<script>
  $(function () {

  });
</script>


