
        <div class="row">
            <div class="col-md-10">
<div class="card card-white">
              <div class="card-header">
                  <div class="row">
                      <label class="col-md-2">
                          Módulo activo
                      </label>
                      <div class="col-md-3">
                          <?php echo Form::dbSelectCripto("x.modulo_id",NULL,NULL,NULL,"class='form-control'")?>
                      </div>
                      <div class="col-md-2 text-right offset-md-5">
                          <button id="agregar" class="btn btn-primary btn-block"> <i class="fa fa-plus"></i> Nuevo Perfil</button>
                      </div>
                  </div>
                <!--<a class="btn btn-primary" href="<?php //echo $link_volver?>">Volver</a>-->
              </div>
                  <?php View::content()?>
                <div class="card-body">
<table id="example" class="table table-striped table-bordered dt-responsive nowrap">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Perfil</th>
                <th>Precio</th>
                <th>Administrador</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
</table>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <!--<button type="submit" class="btn btn-primary">Registrar</button>-->
                </div>
              </form>
            </div>
           </div>
        </div>
        <!-- /.row -->

<script>
    
    $(document).ready(function (){
        ver_modulos();
        
        $("#x_modulo_id").change (function (){
            ver_modulos();
        });
    });
    
   function  ver_modulos()
   {
      let modulo_id = $("#x_modulo_id").val();
      let url= "<?php echo PUBLIC_PATH?>../../sysperfil/ajax_lista";
      let datos = {"modulo_id": modulo_id};
      $.post(url,datos,function (resul){
          console.log(resul);
          $("#example > tbody").html(resul);
      });
   }
  $(function () {
      
      
    $("#example").DataTable({
      "responsive": true,
      "bInfo" : false,
       "paging": false,
      "searching": false,
      //"autoWidth": false,
    });
    
    $("#agregar").click(function (){
        let modulo_id = $("#x_modulo_id").val();
        window.location ="<?php echo $link_add?>"+modulo_id;
    });
//    $('#example2').DataTable({
//      "paging": true,
//      "lengthChange": false,
//      "searching": false,
//      "ordering": true,
//      "info": true,
//      "autoWidth": false,
//      "responsive": true,
//    });
  });
</script>



