
        <div class="row">
            <div class="col-md-6">
<div class="card card-primary">
              <div class="card-header">
                  &nbsp;
                <!--<a class="btn btn-primary" href="<?php //echo $link_volver?>">Volver</a>-->
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.id")?>
                  <div class="form-group">
                    <label for="clave1">Apellido/s</label>
                    <?php echo Form::input("text","a.ape", ' class="form-control" maxlength="30" placeholder="Ingrese el/los apellidos" ')?>
                  </div>
                  <div class="form-group">
                    <label for="clave2">Nombre/s </label>
                    <?php echo Form::input("text","a.nom", ' class="form-control" maxlength="30" placeholder="Ingrese el/los nombres" ')?>
                  </div>
                  <div class="form-group">
                    <label for="clave3">D.N.I. </label>
                    <?php echo Form::input("number","a.dni", ' class="form-control" maxlength="8" placeholder="Ingrese el DNI" ')?>
                  </div>
                  <div class="form-group">
                    <label for="clave3">Celular </label>
                    <?php echo Form::input("text","a.cel", ' class="form-control" maxlength="30" placeholder="Ingrese el Nro de Celular" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_pais">Pais</label>
                    <?php echo Form::select("a.pais", array("+54"=>"Argentina"),' class="form-control" ')?>
                  </div>
                  <div class="form-group">
                    <label for="a_mail">Correo Electrónico </label>
                    <?php echo Form::input("email","a.mail1", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el E-Mail" ', Auth::get("usu"))?>
                  </div>
                    
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Guardar Cambios</button>
                </div>
              </form>
            </div>
           </div>
        </div>
        <!-- /.row -->

<script>
  $(function () {

  });
</script>


