
<div class="row m-1">
    <div class="col-md-6">
        <div class="card card-primary">
            <!--              <div class="card-header">
                              &nbsp;
                            <a class="btn btn-primary" href="<?php //echo $link_volver ?>">Volver</a>
                          </div>-->
            <!-- /.card-header -->
            <!-- form start -->
            <div class="card-body">
                <?php View::content() ?>
                <div class="row">
                    <div class="col-12 col-sm-6 col-md-6 offset-md-3">
                        <div class="info-box mb-3">
                            <span class="info-box-icon bg-primary elevation-1"><i class="fas fa-thumbs-up"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Exitosa</span>
                                <span class="info-box-number">Modificación</span>
                            </div>
                            <!-- /.info-box-content -->
                        </div>
                        <!-- /.info-box -->
                    </div>                    
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <!--<button type="submit" class="btn btn-primary">Cambiar Clave</button>-->
            </div>
        </div>
    </div>
</div>
<!-- /.row -->
