
<div class="row m-1">
    <div class="col-md-3 offset-md-3">
        <div class="card card-primary">
            <!-- form start -->
            <div class="card-body">
                <?php View::content() ?>
<div class="card card-primary card-outline">
              <div class="card-body box-profile">
                <div class="text-center">
                    <a href="#">
                        <img id="imagen" class="img-fluid img-circle" src="<?php echo Usuario::$FOTO?>" alt="User profile picture">
                    </a>
                </div>

                <h3 class="profile-username text-center"><?php echo Usuario::$NOMBRE?></h3>

                <p class="text-muted text-center"><?php echo Auth::get("usu")?></p>
                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" value="ok" name="ok"/>
                    <div class="row">
                        <div class="col-md-6">
                            <button type="boton" class="btn btn-outline-primary btn-block m-1" id="abrir">
                                <i class="fas fa-binoculars"></i>
                                Buscar
                            </button>
                        </div>
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-outline-primary btn-block m-1">
                                <i class="fas fa-camera"></i>
                                Guardar
                            </button>
                        </div>
                    </div>
                    <input type="file" id="seleccionar" name="seleccionar" style = "display: none;">
                </form>
              </div>
              <!-- /.card-body -->
            </div>                
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <!--<button type="submit" class="btn btn-primary">Cambiar Clave</button>-->
            </div>
        </div>
    </div>
</div>
<!-- /.row -->
<script>
  $(document).ready(function (){
      $("#abrir").click(function (e){
          e.preventDefault();
          $("#seleccionar").click();
      });
      $("#imagen").click(function (e){
          e.preventDefault();
          $("#seleccionar").click();
      });
      
      $("#seleccionar").change(function (){
          console.log("Change1");
          readURL(this);
      });
  });
    
    
function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      // Asignamos el atributo src a la tag de imagen
      $('#imagen').attr('src', e.target.result);
    }
    reader.readAsDataURL(input.files[0]);
  }
}

//// El listener va asignado al input
//$("#imagen").change(function() {
//  readURL(this);
//});

</script>
    
    
    