
        <div class="row">
            <div class="col-md-8">
                
            <div class="card ">
              <div class="card-header d-none d-sm-none d-md-block  text-right">
                <a class="btn btn-outline-primary" href="<?php echo $link_volver?>">
                    <i class="fas fa-chevron-left"></i> Volver
                </a>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" method="post">
                <div class="card-body">
                  <?php View::content()?>
                    <?php echo Form::hidden("a.id")?>
                    <?php echo Form::hidden("a.perfil_id")?>
                  <div class="form-group">
                      <label for="a_modulo" class="text-primary"> Módulo Seleccionado</label>
                    <?php echo Form::input("text","a.modulo", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                      <label for="a_modulo" class="text-primary"> Perfil Seleccionado</label>
                    <?php echo Form::input("text","a.perfil", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                      <label for="a_controlador" class="text-primary"> Controlador</label>
                    <?php echo Form::input("text","a.controlador", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                      <label for="a_accion" class="text-primary"> Acción Activa</label>
                    <?php echo Form::input("text","a.accion", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                  <div class="form-group">
                      <label for="a_permitido" class="text-primary"> Acceso</label>
                    <?php echo Form::input("text","a.permitido", 'disabled class="form-control" maxlength="45" placeholder="Ingrese el Controlador" ')?>
                  </div>
                </div>
                  <?php Flash::error("Realmente desea quitar este acceso? Confirmar")?>
                <!-- /.card-body -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-6 m-1">
                            <button type="submit" class="btn btn-outline-danger btn-block">
                                <i class="far fa-trash-alt"></i> 
                                Si, Borrar
                            </button>
                        </div>
                        <div class="col-md-5 m-1">
                            <a class="btn btn-outline-primary btn-block" href="<?php echo $link_volver?>">
                                <i class="fas fa-chevron-left"></i> Volver
                            </a>
                        </div>
                    </div>
                </div>
              </form>
            </div>
                
           </div>
        </div>
        <!-- /.row -->
<script>
    $(document).ready(function (){
        ver_acciones();
       
        $("#a_controlador_id").change(function (){
            ver_acciones();
        });
    });
    
    function ver_acciones()
    {
        var controlador_id = $("#a_controlador_id").val();
        
        var url = "<?php echo PUBLIC_PATH?>../../sysaccion/ajax_combo_norepeat";
        var datos = {"controlador_id": controlador_id};
        console.log(controlador_id);
        $.post(url,datos,function(r){
            console.log(r);
            $("#a_accion_id").html(r);
        });
        
    }
    
    
  $(function () {

  });
</script>

