
        <div class="row">
            <div class="col-md-12">
<div class="card card-white">
              <div class="card-header">
                  <div class="row">
                      <!--<label class="col-md-1">-->
                      <div class="col-md-1">
                          Módulo activo
                      </div>
                      <!--</label>-->
                      <div class="col-md-3">
                          <h5 class="text-bold text-primary"><?php echo $x->modulo?></h5>
                      </div>
                      <div class="col-md-1">
                      <!--<label class="col-md-2">-->
                          Perfil activo
                      </div>
                      <div class="col-md-3">
                          <h5 class="text-bold text-primary"><?php echo $x->perfil?></h5>
                      </div>
                      <div class="col-md-1 text-right">
                          <a class="btn btn-outline-primary btn-block m-1" href="<?php echo $link_volver?>"> <i class="fas fa-chevron-left"></i> Volver</a>
                      </div>
                      <div class="col-md-1 text-right">
                          <a class="btn btn-outline-primary btn-block m-1" href="<?php echo $link_add?>"> <i class="fa fa-plus"></i> Acceso</a>
                      </div>
                  </div>
                <!--<a class="btn btn-primary" href="<?php //echo $link_volver?>">Volver</a>-->
              </div>
                  <?php View::content()?>
                <div class="card-body">
<table id="example" class="table table-striped table-bordered dt-responsive nowrap">
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>Acción</th>
                <th>Controlador</th>
                <th>Accede</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($lista as $value):?>
            <tr>             
                <td>
<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" href="<?php echo ($value->permitido=="S"?$link_nopermitir:$link_permitir). Crypto::e($value->id)?>"><i class="fa fa-edit text-indigo"></i> 
      <?php echo ($value->permitido=="S"?"No Permitir":"Permitir Acceso")?>
      </a>
    <a class="dropdown-item" href="<?php echo $link_del.Crypto::e($value->id)?>"><i class="fa fa-trash text-danger"></i> Borrar</a>
  </div>
</div>                </td>
                <td><?php echo $value->accion?></td>
                <td><?php echo $value->controlador?></td>
                <td><?php echo $value->permitido?></td>
            </tr>
            <?php endforeach;?>
            
        </tbody>
</table>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <!--<button type="submit" class="btn btn-primary">Registrar</button>-->
                </div>
              </form>
            </div>
           </div>
        </div>
        <!-- /.row -->

<script>
    
    $(document).ready(function (){
        //ver_modulos();
        
        $("#x_modulo_id").change (function (){
            //ver_modulos();
        });
    });
    
   function  ver_modulos()
   {
      let modulo_id = $("#x_modulo_id").val();
      let url= "<?php echo PUBLIC_PATH?>../../sysperfil/ajax_lista";
      let datos = {"modulo_id": modulo_id};
      $.post(url,datos,function (resul){
          console.log(resul);
          $("#example > tbody").html(resul);
      });
   }
  $(function () {
      
      
    $("#example").DataTable({
      "responsive": true,
      "bInfo" : false,
       "paging": false,
      "searching": true,
      //"autoWidth": false,
    });
    
    $("#agregar").click(function (){
        let modulo_id = $("#x_modulo_id").val();
        window.location ="<?php echo $link_add?>"+modulo_id;
    });
//    $('#example2').DataTable({
//      "paging": true,
//      "lengthChange": false,
//      "searching": false,
//      "ordering": true,
//      "info": true,
//      "autoWidth": false,
//      "responsive": true,
//    });
  });
</script>



