 <!-- Masthead-->
 <header class="masthead bg-primary text-white text-center" id="inicio">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                <!--<img class="masthead-avatar mb-5" src="assets/img/avataaars.svg" alt="" />-->
                <img class="masthead-avatar mb-5" src="<?php echo PUBLIC_PATH?>img/lupa256.png" alt="" />
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">¿DONDE ESTA MI DINERO?</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-money-bill-wave" style="color: #de8c00;"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                <p class="masthead-subheading font-weight-light mb-0">Cuide las monedas, que los billetes se cuidan solos...</p>
            </div>
        </header> 

