<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>Y Mi Dinero?</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicons -->
    <link href="<?php echo PUBLIC_PATH?>img/signo-pesos256.png" rel="icon">
    <link href="<?php echo PUBLIC_PATH?>img/signo-pesos256.png" rel="apple-touch-icon">  
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="<?php echo PUBLIC_PATH?>freelancer/css/styles.css" rel="stylesheet" />


</head>
 <body id="page-top">
  <?php View::partial('externo/menu') ?>
  <?php View::content() ?>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
<!--    <script src="assets/mail/jqBootstrapValidation.js"></script>
        <script src="assets/mail/contact_me.js"></script>
      -->
        <!-- Core theme JS-->
        <script src="<?php echo PUBLIC_PATH?>freelancer/js/scripts.js"></script>
</body>
</html>
