<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>Y Mi Dinero?</title>
    <link href="<?php echo PUBLIC_PATH?>img/signo-pesos256.png" rel="icon">
    <link href="<?php echo PUBLIC_PATH?>img/signo-pesos256.png" rel="apple-touch-icon">  
<meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH?>plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH?>plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH?>plugins/toastr/toastr.min.css">  
  <!-- DataTables -->
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH?>plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH?>plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/venobox/1.9.3/venobox.min.css" />  
  <!-- Theme style -->
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH?>plugins/dist/css/adminlte.min.css">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


<!-- jQuery -->
<script src="<?php echo PUBLIC_PATH?>plugins/jquery/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/venobox/1.9.3/venobox.min.js" ></script>
<script src="<?php echo PUBLIC_PATH?>plugins/toastr/toastr.min.js"></script>
<!-- Bootstrap 4 -->
<script src="<?php echo PUBLIC_PATH?>plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- InputMask -->
<script src="<?php echo PUBLIC_PATH?>plugins/moment/moment.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="<?php echo PUBLIC_PATH?>plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- AdminLTE App -->


</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
 <?php View::partial("interno/sup",NULL,array("titulo"=>$titulo))?>
 <?php View::partial("interno/izq")?>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- /.card -->
         <?php View::content() ?>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
   <?php View::partial("interno/footer")?>
   <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->
        
<!-- DataTables -->
<script src="<?php echo PUBLIC_PATH?>plugins/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo PUBLIC_PATH?>plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="<?php echo PUBLIC_PATH?>plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="<?php echo PUBLIC_PATH?>plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

    <script src="<?php echo PUBLIC_PATH?>plugins/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo PUBLIC_PATH?>plugins/dist/js/demo.js"></script>
</body>
</html>
