 <!-- Header -->
  <header class="masthead bg-primary text-white text-center">
    <div class="container">
        <?php View::content()?>
      <img class="img-fluid mb-5 d-block mx-auto" src="<?php echo PUBLIC_PATH?>img/lupa256.png" alt="">
      <h1 class="text-uppercase mb-0">Mi dinero esta bien invertido?</h1>
      <hr class="star-light">
      <h2 class="font-weight-light mb-0">Cuida de los pequeños gastos; un pequeño agujero hunde un barco...(BF)</h2>
    </div>
  </header>